[package]
authors = ["nathanielsimard <nathaniel.simard.42@gmail.com>"]
categories = ["science"]
description = "WGPU backend for the Burn framework"
edition.workspace = true
keywords = ["deep-learning", "machine-learning", "gpu", "wgpu", "webgpu"]
license.workspace = true
name = "burn-wgpu"
readme.workspace = true
repository = "https://github.com/tracel-ai/burn/tree/main/crates/burn-wgpu"
version.workspace = true

[features]
default = ["fusion", "burn-jit/default", "cubecl/default"]
fusion = ["burn-fusion", "burn-jit/fusion"]
autotune = ["burn-jit/autotune"]
template = ["burn-jit/template", "cubecl/template"]
doc = ["burn-jit/doc"]
std = ["burn-jit/std"]

[dependencies]
cubecl = { workspace = true, features = ["wgpu"] }

burn-jit = { path = "../burn-jit", version = "0.14.0", default-features = false }
burn-tensor = { path = "../burn-tensor", version = "0.14.0", features = ["cubecl-wgpu"] }
burn-fusion = { path = "../burn-fusion", version = "0.14.0", optional = true }

[dev-dependencies]
burn-jit = { path = "../burn-jit", version = "0.14.0", default-features = false, features = [
  "export_tests",
] }
