[book]
authors = [
    "Wouter Doppenberg",
    "Nathaniel Simard",
    "Louis Fortier-Dubois",
    "Dilshod Tadjibaev",
    "Guillaume Lagrange",
    "Sylvain Benner",
]
language = "en"
multilingual = false
src = "src"
title = "The Burn Book 🔥"
